# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kind Squared Error
tagline:          'A Jekyll theme'
description:      'Make mistakes, take notes, learn exponentially. Compiled by Jason Sohn'
url:              http://neuroquantifier.github.io/
baseurl:          /

author:
  name:           'Jason Sohn'
  url:            https://github.com/neuroquantifier

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/neuroquantifier
